message:
  owner: config-service's native folder main
  content: :) 안녕하세요 각각의 마이크로서비스에서 사용될 데이터입니다. :)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pplus?useSSL=false&serverTimezone=Asia/Seoul
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: "{cipher}1a20b8b280d27de16764cd4423d44f8dd305a8d412e1c85672e23c857b899861"

jwt:
  token:
    key: "{cipher}e0b6738eb0fa6626cc50002deb2a7c7bd8168e770c23273d1ff97e36cedfdbd91321104d58f31414b194d2824350fa8a"
