message:
  owner: config-service's native folder main
  content: :) 안녕하세요 각각의 마이크로서비스에서 사용될 데이터입니다. :)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?autoReconnect=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "{cipher}fc564c5cc130cce00f99393860cd78abbaf1b994bb7c51ba7cf3aa181255aaaf"
  jpa:
    show-wql: true
    properties:
      hibernate:
         format_sql: true
 

jwt:
  token:
    key: "{cipher}e2777829f7bf2d78ff370448c4bcd0c434dccf0e343b11dfcfe39cf248df12adeabf729fc9b515d8d089c5121340f1cc4d27c7c98653055f92ac021199dead67"
    expiration_time: 3600
