message:
  owner: config-service's native folder stage
  content: :) 안녕하세요 각각의 마이크로서비스에서 사용될 데이터입니다. :)

spring:
  datasource:
    url: dbUrl
    driver: com.h2.Driver
    username: admin_stage
    password: admin!!!

jwt:
  token:
    key: "{cipher}e0b6738eb0fa6626cc50002deb2a7c7bd8168e770c23273d1ff97e36cedfdbd91321104d58f31414b194d2824350fa8a"
